---
# Tasks specific for OpenSuse Systems

- name: "Suse | add http_proxy in proxy"
  lineinfile: dest=/etc/sysconfig/proxy regexp='^HTTP_PROXY="' line='HTTP_PROXY={{ ansible_http_proxy }}'
- name: "Suse | add https_proxy in proxy"
  lineinfile: dest=/etc/sysconfig/proxy regexp='^HTTPS_PROXY="' line='HTTPS_PROXY={{ ansible_https_proxy }}'

- name: "Suse | Install basic repo file"
  zypper_repository: repo="http://download.opensuse.org/repositories/server:monitoring/SLE_{{ ansible_distribution_major_version }}_SP{{ ansible_distribution_release }}/server:monitoring.repo" disable_gpg_check=yes state=present
  when: zabbix_repo == "zabbix" and ansible_distribution == "SLES"
  become: yes
  tags:
    - zabbix-agent
    - init

- name: "Suse | Install basic repo file"
  zypper_repository: repo="http://download.opensuse.org/repositories/server:monitoring/openSUSE_{{ ansible_distribution_version }}/server:monitoring.repo"
  when: zabbix_repo == "zabbix" and ansible_distribution != "SLES"
  become: yes
  tags:
    - zabbix-agent
    - init

- name: "Suse | Install zabbix-agent"
  zypper: name={{ zabbix_agent_package }}
          state={{ zabbix_agent_package_state }}
          disable_gpg_check=yes
  become: yes
  tags:
    - zabbix-agent
    - init

